export const DEVICE_LIST_REQUEST = "DEVICE_LIST_REQUEST";
export const DEVICE_LIST_SUCCESS = "DEVICE_LIST_SUCCESS";
export const DEVICE_LIST_FAIL = "DEVICE_LIST_FAIL";

export const DEVICE_LIVEDATA_REQUEST = "DEVICE_LIVEDATA_REQUEST";
export const DEVICE_LIVEDATA_SUCCESS = "DEVICE_LIVEDATA_SUCCESS";
export const DEVICE_LIVEDATA_FAIL = "DEVICE_LIVEDATA_FAIL";

export const DASHBOARD_DATA_REQUEST = "DASHBOARD_DATA_REQUEST";
export const DASHBOARD_DATA_SUCCESS = "DASHBOARD_DATA_SUCCESS";
export const DASHBOARD_DATA_FAIL = "DASHBOARD_DATA_FAIL";

export const DEVICE_DATA_REQUEST = "DEVICE_DATA_REQUEST";
export const DEVICE_DATA_SUCCESS = "DEVICE_DATA_SUCCESS";
export const DEVICE_DATA_FAIL = "DEVICE_DATA_FAIL";

export const DEVICE_DETAILS_REQUEST = "DEVICE_DETAILS_REQUEST";
export const DEVICE_DETAILS_SUCCESS = "DEVICE_DETAILS_SUCCESS";
export const DEVICE_DETAILS_FAIL = "DEVICE_DETAILS_FAIL";
