export const ORGANIZATION_LIST_REQUEST = "ORGANIZATION_LIST_REQUEST";
export const ORGANIZATION_LIST_SUCCESS = "ORGANIZATION_LIST_SUCCESS";
export const ORGANIZATION_LIST_FAIL = "ORGANIZATION_LIST_FAIL";

// Add Organization
export const ORGANIZATION_ADD_REQUEST = "ORGANIZATION_ADD_REQUEST"
export const ORGANIZATION_ADD_SUCCESS = "ORGANIZATION_ADD_SUCCESS"
export const ORGANIZATION_ADD_FAIL = "ORGANIZATION_ADD_FAIL"
