export const SENSOR_LIST_REQUEST = "SENSOR_LIST_REQUEST";
export const SENSOR_LIST_SUCCESS = "SENSOR_LIST_SUCCESS";
export const SENSOR_LIST_FAIL = "SENSOR_LIST_FAIL";

export const SENSOR_PARAMETER_REQUEST = 'SENSOR_PARAMETER_REQUEST'
export const SENSOR_PARAMETER_SUCCESS = 'SENSOR_PARAMETER_SUCCESS'
export const SENSOR_PARAMETER_FAIL = 'SENSOR_PARAMETER_FAIL'
