export const SENSOR_LIST_REQUEST = "SENSOR_LIST_REQUEST";
export const SENSOR_LIST_SUCCESS = "SENSOR_LIST_SUCCESS";
export const SENSOR_LIST_FAIL = "SENSOR_LIST_FAIL";

export const SENSOR_PARAMETER_REQUEST = "SENSOR_PARAMETER_REQUEST";
export const SENSOR_PARAMETER_SUCCESS = "SENSOR_PARAMETER_SUCCESS";
export const SENSOR_PARAMETER_FAIL = "SENSOR_PARAMETER_FAIL";

export const LIVE_DATA_REQUEST = "LIVE_DATA_REQUEST";
export const LIVE_DATA_SUCCESS = "LIVE_DATA_SUCCESS";
export const LIVE_DATA_FAIL = "LIVE_DATA_FAIL";

export const SAMPLE_GRAPH_REQUEST = "SAMPLE_GRAPH_REQUEST";
export const SAMPLE_GRAPH_SUCCESS = "SAMPLE_GRAPH_SUCCESS";
export const SAMPLE_GRAPH_FAIL = "SAMPLE_GRAPH_FAIL";
